openapi: 3.0.2
info:
  title: demo-service
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /users:
    post:
      operationId: addUser
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Успех
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultWithId'
        default:
          description: Ошибка
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{id}:
    get:
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Успех
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Ошибка
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        202:
          description: Успех
  /users/{id}/tasks:
    get:
      operationId: getAllTasksByUserId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Успех
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/GetAllTasksByUserIdResponse'
        default:
          description: Ошибка
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: addTaskToUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Успех
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultWithId'
        default:
          description: Ошибка
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetAllTasksByUserIdResponse:
      type: array
      items:
        $ref: '#/components/schemas/TaskWithId'
    TaskWithId:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
        - $ref: '#/components/schemas/Task'
    ResultWithId:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
    Task:
      type: object
      required:
        - name
        - dateTime
      properties:
        name:
          type: string
        dateTime:
          type: string
          format: 'date-time'
    User:
      type: object
      required:
        - name
        - login
        - password
      properties:
        name:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string