DROP DATABASE IF EXISTS todo;
DROP USER IF EXISTS todo;

CREATE USER todo WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    CREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'todo';

CREATE DATABASE todo
    WITH OWNER = todo
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT CONNECT ON DATABASE todo TO todo;
