db:
  demo:
    host: localhost
    port: 5432
    name: demo
    username: postgres
    password: postgres

logging.level:
  ru.craftysoft: trace
  ru.craftysoft.demoservice: trace
  reactor.netty.http.server: info