db:
  demo:
    host: localhost
    port: 5432
    name: todo
    username: todo
    password: todo

rest:
  demo:
    url: http://localhost:8080

server:
  port: 8080

logging.level:
  ru.craftysoft: trace
  ru.craftysoft.demoservice: trace
  reactor.netty.http.server: info